//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacoSuccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custombuild
    {
        public int entreeID { get; set; }
        public int itemID { get; set; }
        public int ingredientsID { get; set; }
        public decimal buildPrice { get; set; }
        public int quantity { get; set; }
    }
}
