//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacoSuccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entree
    {
        public int entreeID { get; set; }
        public int categoryID { get; set; }
        public string entreeName { get; set; }
        public string description { get; set; }
        public decimal entreePrice { get; set; }
        public string imagePath { get; set; }
    }
}
