//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacoSuccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        public int ingredientsID { get; set; }
        public int vendorID { get; set; }
        public string ingredientsCode { get; set; }
        public string ingredientsName { get; set; }
        public int qtyOnHand { get; set; }
        public System.DateTime dateAdded { get; set; }
        public Nullable<int> markupPercent { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
