//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacoSuccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderID { get; set; }
        public int stationID { get; set; }
        public int customerID { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal taxAmount { get; set; }
        public int cardType { get; set; }
        public string cardNumber { get; set; }
        public string cardExpress { get; set; }
        public int billingAddressID { get; set; }
    }
}
