//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacoSuccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int detailsID { get; set; }
        public int orderID { get; set; }
        public int customBuildID { get; set; }
        public int entreeID { get; set; }
        public int ingredientsID { get; set; }
        public decimal orderPrice { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
